module.exports = {
  apps: [
    {
      name: "sskind-backend",
      script: "main.py",
      interpreter: "/Users/wang.13246/.local/share/mamba/envs/sskind/bin/python",
      cwd: "/Users/wang.13246/Documents/GitHub/ssKIND-backend",
      env: {
        HOST: "0.0.0.0",
        PORT: "9117",
        NODE_ENV: "production",
        DEBUG: "False",
        RELOAD: "False",
        DATABASE_URL: "sqlite:///./app.db",
        GLOBAL_PREFIX: "/sskind-backend",
        API_PREFIX: "/api/v1",
        DOCS_URL: "/docs",
        REDOC_URL: "/redoc",
        CORS_ORIGINS: '["*"]',
        CORS_CREDENTIALS: "True",
        CORS_METHODS: '["*"]',
        CORS_HEADERS: '["*"]',
        APP_TITLE: "ssKIND Backend API",
        APP_DESCRIPTION:
          "Spatial and single-cell RNA-seq data API for neuroscience research",
        APP_VERSION: "1.0.0",
      },
      env_development: {
        HOST: "0.0.0.0",
        PORT: "9117",
        NODE_ENV: "development",
        DEBUG: "True",
        RELOAD: "True",
        DATABASE_URL: "sqlite:///./app.db",
        GLOBAL_PREFIX: "/sskind-backend",
        API_PREFIX: "/api/v1",
        DOCS_URL: "/docs",
        REDOC_URL: "/redoc",
        CORS_ORIGINS: '["*"]',
        CORS_CREDENTIALS: "True",
        CORS_METHODS: '["*"]',
        CORS_HEADERS: '["*"]',
        APP_TITLE: "ssKIND Backend API (Dev)",
        APP_DESCRIPTION:
          "Spatial and single-cell RNA-seq data API for neuroscience research - Development",
        APP_VERSION: "1.0.0-dev",
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "1G",
      error_file: "./logs/err.log",
      out_file: "./logs/out.log",
      log_file: "./logs/combined.log",
      time: true,
      autorestart: true,
      restart_delay: 1000,
      max_restarts: 10,
      min_uptime: "10s",
      kill_timeout: 5000,
      listen_timeout: 3000,
      // Additional PM2 settings
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],

  deploy: {
    production: {
      user: "wang.13246",
      host: "localhost",
      ref: "origin/main",
      repo: "git@github.com:your-username/ssKIND-backend.git",
      path: "/Users/wang.13246/Documents/GitHub/ssKIND-backend",
      "pre-deploy-local": "",
      "post-deploy":
        "npm install && pm2 reload ecosystem.config.js --env production",
      "pre-setup": "",
    },
  },
};
