module.exports = {
  apps: [
    {
      name: "hypomap-backend",
      script: "main.py",
      interpreter: "/home/wan268/micromamba/envs/hypomap/bin/python",
      cwd: "/server/nodejs/hypomap-backend",
      env: {
        HOST: "0.0.0.0",
        PORT: "9120",
        NODE_ENV: "production",
        DEBUG: "False",
        RELOAD: "False",
        DATABASE_URL: "sqlite:///./app.db",
        GLOBAL_PREFIX: "/hypomap-backend",
        API_PREFIX: "/api/v1",
        DOCS_URL: "/docs",
        REDOC_URL: "/redoc",
        CORS_ORIGINS: '["*"]',
        CORS_CREDENTIALS: "True",
        CORS_METHODS: '["*"]',
        CORS_HEADERS: '["*"]',
        APP_TITLE: "HypoMap Backend API",
        APP_DESCRIPTION: "Single-cell RNA-seq analysis with AI-powered hypothesis generation",
        APP_VERSION: "1.0.0",
      },
      env_development: {
        HOST: "0.0.0.0",
        PORT: "9120",
        NODE_ENV: "development",
        DEBUG: "True",
        RELOAD: "True",
        DATABASE_URL: "sqlite:///./app.db",
        GLOBAL_PREFIX: "/hypomap-backend",
        API_PREFIX: "/api/v1",
        DOCS_URL: "/docs",
        REDOC_URL: "/redoc",
        CORS_ORIGINS: '["*"]',
        CORS_CREDENTIALS: "True",
        CORS_METHODS: '["*"]',
        CORS_HEADERS: '["*"]',
        APP_TITLE: "HypoMap Backend API (Dev)",
        APP_DESCRIPTION: "Single-cell RNA-seq analysis with AI - Development",
        APP_VERSION: "1.0.0-dev",
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "2G",
      error_file: "./logs/err.log",
      out_file: "./logs/out.log",
      log_file: "./logs/combined.log",
      time: true,
      autorestart: true,
      restart_delay: 1000,
      max_restarts: 10,
      min_uptime: "10s",
      kill_timeout: 5000,
      listen_timeout: 3000,
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
  ],

  deploy: {
    production: {
      user: "wan268",
      host: "bmblx.bmi.osumc.edu",
      ref: "origin/main",
      repo: "git@github.com:Wang-Cankun/hypomap-backend.git",
      path: "/server/nodejs",
      "pre-deploy-local": "",
      "post-deploy":
        "cd hypomap-backend && pip install -r requirements.txt && pm2 reload ecosystem.config.js --env production",
      "pre-setup": "",
    },
  },
};
